### PR TITLE
Revert unredirection backports

### PR DESCRIPTION
**Pull request by clefebvre**
and commits related to layout.js optimizations in Cinnamon.

Depends on https://github.com/linuxmint/cinnamon/pull/8624.

This reverts the commits below (in green) and makes muffin much more similar to iter-20 than before:

image

Reverting https://github.com/linuxmint/muffin/commit/1d01e839d55239e5cad0a8498017b25079474c61 guarantees the crash on meta_window_actor_should_unredirect won't occur anymore (we got conflicting feedback on whether https://github.com/linuxmint/muffin/commit/e2d4bd47d70add68e53165e62cd59b9273b7003b fixed it... it should, but we can't say 100% since we know how to reliably reproduce the issue) and prevents issues related to the screensaver from occuring again.

Although the screensaver always requested an unredirection we believe it was composited in 4.0. With the introduction of https://github.com/linuxmint/muffin/commit/1d01e839d55239e5cad0a8498017b25079474c61, it started to be properly unredirected and this caused issues of lag and non-responsiveness in the screensaver. We've got two potential workarounds/solutions for this, but neither have been thoroughly tested yet:

- https://github.com/linuxmint/muffin/pull/510 (composites the screensaver)
- https://github.com/linuxmint/cinnamon-screensaver/pull/309 (removes the fader animation in the screensaver)

### CODE REVIEW

**Comment by jaszhix** [comment]
This is textbook overkill, you just had to let me work on this for another week. I had one week of work in on this after a long break in May from my job, then laid off. Thanks for wasting my time @clefebvre.

**Comment by jaszhix** [comment]
Also, muffin is blocked from freesync precisely for this reason. You are blocking muffin's compatibility with how applications want to be run because the screensaver can't work unredirected. If there is an open source equivalent of idiocracy, this is it.

https://www.phoronix.com/scan.php?page=news_item&px=AMD-V4-Adaptive-VRR-FreeSync

**Comment by jaszhix** [comment]
sorry, opened all my PRs in tabs and thought I was closing my own. carry on

**Comment by clefebvre** [comment]
no pb

**Comment by pizzadude** [comment]
This commit improved performance a lot in games on my laptop which is old. It's a shame that it had to get reverted. :P

**Comment by pizzadude** [comment]
@clefebvre I'm not a programmer, but would it be possible to force the screensaver to be composited instead of reverting this commit?

**Comment by brownsr** [comment]
@pizzadude That is one of the future workarounds/solutions mentioned above.  Right now it is important that we have a stable product ready for release.  That means that some changes and improvements may get bumped to the next development cycle.  Sorry about that, but we do plan to come back to this.

Regards

Simon

**Comment by pizzadude** [comment]
@brownsr Alright. I understand that stability is more important than performance, especially in a distro like Linux Mint. I appreciate all your hard work! :)

**Comment by clefebvre** [comment]
@pizzadude add info about your hardware and the games in question in https://github.com/linuxmint/cinnamon/issues/8625. That way we'll be able to reproduce the perf boost when looking at that commit again. Focus on free games if possible (to make sure other devs have them) and explain where/how you see the performance difference.

**Comment by pizzadude** [comment]
@clefebvre The problem is that it's almost every game I have installed on this (old) laptop (mostly low end / old games), from games like Super Hexagon / Super Meat Boy, to games like Quake 3, all run smoothly with the unredirect fullscreen windows option, which only sometimes worked before the patch that fixed that (which are now reverted). Now, just like before in the stable cinnamon unredirect only works temporarily when restarting cinnamon or when closing / opening the laptop lid (resuming from suspend).

The hardware in question is very low end, that is the reason that the unredirect option was required for good performance:

Kernel: Linux 5.0.0-16-generic x86_64
Distro: Linux Mint 19.1 Tessa
CPU:    Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
        4 cores/threads
        2400.00 MHz
RAM:    7.58 GiB
GPU:    Mesa DRI Intel(R) Ironlake Mobile 
        OpenGL 2.1 Mesa 19.0.1 - padoka PPA
        GLSL 1.20

**Pull request merged**
