### PR TITLE
Gtk 3.16 fixes - added fallback metacity theme and render existing ones properly

### PR DESCRIPTION
**Pull request by dalcde**

### CODE REVIEW

**Comment by CtrlC-Root** [comment]
:+1: I'm experiencing this issue as well.

**Comment by ycny** [comment]
Me too. If you need logs/information, just ask.

**Comment by dalcde** [comment]
Sorry what exactly are you experiencing?

**Comment by ycny** [comment]
The same issue as here: https://github.com/linuxmint/Cinnamon/issues/4032

Cinnamon is starting in fallback mode after last system update. I'm using 64-bit Arch linux. Below, you can find logs from package manager with package updated before this issue happen:

```
[PACMAN] starting full system upgrade
[ALPM] transaction started
[ALPM] upgraded glib2 (2.42.2-1 -> 2.44.0-1)
[ALPM] upgraded adwaita-icon-theme (3.14.1-1 -> 3.16.0-1)
[ALPM] upgraded at-spi2-core (2.14.1-1 -> 2.16.0-1)
[ALPM] upgraded atk (2.14.0-1 -> 2.16.0-1)
[ALPM] upgraded at-spi2-atk (2.14.1-1 -> 2.16.0-1)
[ALPM] upgraded icu (54.1-1 -> 55.1-1)
[ALPM] upgraded boost-libs (1.57.0-3 -> 1.57.0-4)
[ALPM] upgraded boost (1.57.0-3 -> 1.57.0-4)
[ALPM] installed gobject-introspection-runtime (1.44.0-1)
[ALPM] upgraded pygobject-devel (3.14.0-2 -> 3.16.0-1)
[ALPM] upgraded harfbuzz (0.9.40-1 -> 0.9.40-2)
[ALPM] upgraded python2-gobject (3.14.0-2 -> 3.16.0-1)
[ALPM] installed python2-markupsafe (0.23-2)
[ALPM] installed python2-beaker (1.6.5-1)
[ALPM] installed python2-mako (1.0.1-1)
[ALPM] upgraded gobject-introspection (1.42.0-1 -> 1.44.0-1)
[ALPM] upgraded python2-atspi (2.12.0-1 -> 2.16.0-1)
[ALPM] upgraded gsettings-desktop-schemas (3.14.1-1 -> 3.16.0-1)
[ALPM] upgraded glib-networking (2.42.1-1 -> 2.44.0-1)
[ALPM] upgraded libsoup (2.48.1-1 -> 2.50.0-1)
[ALPM] upgraded rest (0.7.92-1 -> 0.7.93-1)
[ALPM] upgraded dconf (0.22.0-1 -> 0.24.0-1)
[ALPM] upgraded gtk3 (3.14.9-1 -> 3.16.1-1) <==== GTK upgrade ==========
[ALPM] upgraded libgee (0.16.1-1 -> 0.18.0-1)
[ALPM] upgraded clutter (1.20.0-4 -> 1.22.0-2)
[ALPM] upgraded caribou (0.4.17-1 -> 0.4.18-1)
[ALPM] upgraded clutter-gtk (1.6.0-1 -> 1.6.0-2)
[ALPM] upgraded p7zip (9.38.1-1 -> 9.38.1-2)
[ALPM] upgraded file-roller (3.14.2-2 -> 3.16.0-1)
[ALPM] upgraded firefox (37.0.1-1 -> 37.0.1-2)
[ALPM] upgraded glibmm (2.42.0-1 -> 2.44.0-1)
[ALPM] upgraded gnome-backgrounds (3.14.1-1 -> 3.16.0-1)
[ALPM] upgraded gtksourceview3 (3.14.3-1 -> 3.16.0-1)
[ALPM] upgraded gnome-calculator (3.14.1-1 -> 3.16.0-1)
[ALPM] upgraded pangomm (2.34.0-1 -> 2.36.0-1)
[ALPM] upgraded gtkmm3 (3.14.0-1 -> 3.16.0-1)
[ALPM] upgraded gnome-system-monitor (3.14.1-1 -> 3.16.0-1)
[ALPM] upgraded gnome-themes-standard (3.14.2.3-1 -> 3.16.0-1)
[ALPM] upgraded gvfs (1.22.3-2 -> 1.24.0-1)
[ALPM] upgraded harfbuzz-icu (0.9.40-1 -> 0.9.40-2)
[ALPM] upgraded lib32-glib2 (2.42.2-1 -> 2.44.0-1)
[ALPM] upgraded lib32-atk (2.14.0-1 -> 2.16.0-1)
[ALPM] upgraded libssh2 (1.4.3-2 -> 1.5.0-1)
[ALPM] upgraded lib32-libssh2 (1.4.3-2 -> 1.5.0-1)
[ALPM] upgraded lib32-libtasn1 (4.3-1 -> 4.4-1)
[ALPM] upgraded lib32-util-linux (2.25.2-1 -> 2.26-1)
[ALPM] upgraded libcdr (0.1.1-1 -> 0.1.1-2)
[ALPM] upgraded libe-book (0.1.2-1 -> 0.1.2-2)
[ALPM] upgraded libmspub (0.1.2-1 -> 0.1.2-2)
[ALPM] upgraded poppler (0.31.0-1 -> 0.32.0-1)
[ALPM] upgraded libvisio (0.1.1-1 -> 0.1.1-2)
[ALPM] upgraded raptor (2.0.15-1 -> 2.0.15-2)
[ALPM] upgraded libreoffice-fresh (4.4.1-2 -> 4.4.2-1)
[ALPM] upgraded webkitgtk (2.4.8-1 -> 2.4.8-2)
[ALPM] transaction completed
```

And here is systemd journal:
```
org.a11y.Bus[762]: Successfully activated service 'org.a11y.atspi.Registry'
org.a11y.atspi.Registry[769]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
polkitd[391]: Registered Authentication Agent for unix-session:c2 (system bus name :1.37 [/usr/lib/polkit-gnome/polkit-gnome-a
cinnamon-session[756]: WARNING: Application 'cinnamon.desktop' killed by signal 15
systemd-coredump[822]: Process 808 (cinnamon) of user 1000 dumped core.
systemd-coredump[843]: Process 837 (cinnamon) of user 1000 dumped core.
cinnamon-session[756]: WARNING: App 'cinnamon.desktop' respawning too quickly
cinnamon-session[756]: CRITICAL: We failed, but the fail whale is dead. Sorry....
```

**Comment by dalcde** [comment]
Read http://github.com/linuxmint/cinnamon/issues/4039 for fixes and discussion.

**Pull request merged**
