### PR TITLE
[WIP] window-actor: Fix and refactor window effects handling

### PR DESCRIPTION
**Pull request by jaszhix**
Ref https://github.com/linuxmint/cinnamon/issues/8454

### CODE REVIEW

**Comment by JosephMcc** [comment]
Running this locally. It's an improvement over master. Mintupdate is better but still initially maps to the wrong position before moving to the correct place. But the weird texture/shadow issue is fixed in this branch.

The window close animations are also improved over master but still seem to be lacking some smoothness we had a higher speeds in 4.0

**Comment by clefebvre** [comment]
Quick note about mintupdate, it has code to move/resize its own window... so it's possible it looked like that in 4.0 too.

**Comment by clefebvre** [comment]
@jaszhix same observation for me than @JosephMcc in regards to mintupdate (and pkexec xed), the window/dialog isn't squashed anymore, but the window moves after it's mapped.

This doesn't happen with the 4.0 build.

**Comment by jaszhix** [comment]
Replaced by #449, #453, #460, #463, and #464.

**Pull request closed without merging**
