### PR TITLE
window: Fix the snap OSD getting stuck

### PR DESCRIPTION
**Pull request by jaszhix**
Ref https://github.com/linuxmint/cinnamon/issues/8454

### CODE REVIEW

**Comment by JosephMcc** [comment]
Ok, I gave this a quick test. I can no longer reproduce the stuck OSD but it brings new problems. If I move to one side of the screen that pulls up the small tile zone indicator but not far enough to bring up the actual tile preview, the tile preview will not show if I move all the way to the edge.

In addition now when moving directly to the edge I get both the small indicator and the tile preview.

**Comment by mtwebster** [comment]
For posterity:


i see the same thing @joseph noticed in the 450 patch, i noticed this commit https://github.com/linuxmint/muffin/commit/9b849444303c72f14bd1c68b104db1a01ff56139 - which is from 4.0 (i dont even know if this commit is relevant, but it does concern the previews/hud).  i'll play around some more tomorrow.

mtwebster [10:25 PM]
i tried master with that reverted, it seems identical to the current behavior (stuck text window), which i guess it was intended to fix in the first place (and must have been occurring already in 4.0 then)
ok tomorrow

mtwebster [10:30 PM]
ok one thing to state, the current master behavior (other than the stuck text window) is 'correct' - you get the little edge blob when you get close, and the full window-sized preview once you reach the edge (with the blob fading out as well).
the only thing i don't remember - and either way i don't care, is if the full preview was over or under the grabbed window
the blob appears over the window, but the preview slides out under.  i don't remember if that's different or not, but I think it's ok as it is

**Comment by JosephMcc** [comment]
I'm fairly certain at least at one point the preview was below the window. At least it was intended to be that way.

**Comment by clefebvre** [comment]
I can confirm the tile preview (i.e. the big one) should be behind the window, and it is. Arguably the little one (the hud preview) could be behind as well (it's on top on master, and I think it was on top in the past as well), I don't think that needs to be fixed or worried about in the scope of this PR though.

**Comment by clefebvre** [comment]
I see the same issues as @mtwebster and @JosephMcc as well.

**Comment by jaszhix** [comment]
In Cinnamon, I replaced the deprecated `raise_top` method with `parent.set_child_above_sibling`.

https://github.com/linuxmint/cinnamon/commit/394b97c253f166dd060359e993a7f912b9fea4b4#diff-3411cdb80aaaddfcaa2c6d036a436b69L147

If it was broken before, I just fixed it to work as originally intended. I use tiling every day, and don't see any regressions from this PR.

**Comment by jaszhix** [comment]
If what you're talking about is the tile HUD not popping up as quickly (and it still pops up before the window reaches the edge for me), we should really determine if that's something we need and users want. This PR improves window dragging smoothness for me, something I know @JosephMcc has been complaining about since I started touching muffin. I can't really make the HUD appear any sooner without calling into JS more, which makes the elastic effect on window dragging worse.

**Pull request merged**
